export interface Country {
  name: string;
  en: string;
  code: string;
  flag: string;
  isMajor?: boolean;
}

/** 한국 체류 외국인 비중 및 E-9 고용허가제 주요 송출국 등 */
export const MAJOR_COUNTRIES: Country[] = [
  { name: '베트남', en: 'Vietnam', code: 'VN', flag: '🇻🇳', isMajor: true },
  { name: '캄보디아', en: 'Cambodia', code: 'KH', flag: '🇰🇭', isMajor: true },
  { name: '태국', en: 'Thailand', code: 'TH', flag: '🇹🇭', isMajor: true },
  { name: '인도네시아', en: 'Indonesia', code: 'ID', flag: '🇮🇩', isMajor: true },
  { name: '네팔', en: 'Nepal', code: 'NP', flag: '🇳🇵', isMajor: true },
  { name: '필리핀', en: 'Philippines', code: 'PH', flag: '🇵🇭', isMajor: true },
  { name: '미얀마', en: 'Myanmar', code: 'MM', flag: '🇲🇲', isMajor: true },
  { name: '몽골', en: 'Mongolia', code: 'MN', flag: '🇲🇳', isMajor: true },
  { name: '스리랑카', en: 'Sri Lanka', code: 'LK', flag: '🇱🇰', isMajor: true },
  { name: '우즈베키스탄', en: 'Uzbekistan', code: 'UZ', flag: '🇺🇿', isMajor: true },
  { name: '중국', en: 'China', code: 'CN', flag: '🇨🇳', isMajor: true },
  { name: '방글라데시', en: 'Bangladesh', code: 'BD', flag: '🇧🇩', isMajor: true },
  { name: '파키스탄', en: 'Pakistan', code: 'PK', flag: '🇵🇰', isMajor: true },
  { name: '키르기스스탄', en: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬', isMajor: true },
  { name: '라오스', en: 'Laos', code: 'LA', flag: '🇱🇦', isMajor: true },
  { name: '동티모르', en: 'Timor-Leste', code: 'TL', flag: '🇹🇱', isMajor: true },
];

/** 전 세계 모든 국가 (UN 회원국 및 주요 자치령 200여 개국, 가나다순) */
export const ALL_COUNTRIES: Country[] = [
  { name: '가나', en: 'Ghana', code: 'GH', flag: '🇬🇭' },
  { name: '가봉', en: 'Gabon', code: 'GA', flag: '🇬🇦' },
  { name: '가이아나', en: 'Guyana', code: 'GY', flag: '🇬🇾' },
  { name: '감비아', en: 'Gambia', code: 'GM', flag: '🇬🇲' },
  { name: '과테말라', en: 'Guatemala', code: 'GT', flag: '🇬🇹' },
  { name: '괌', en: 'Guam', code: 'GU', flag: '🇬🇺' },
  { name: '그레나다', en: 'Grenada', code: 'GD', flag: '🇬🇩' },
  { name: '그리스', en: 'Greece', code: 'GR', flag: '🇬🇷' },
  { name: '기니', en: 'Guinea', code: 'GN', flag: '🇬🇳' },
  { name: '기니비사우', en: 'Guinea-Bissau', code: 'GW', flag: '🇬🇼' },
  { name: '나미비아', en: 'Namibia', code: 'NA', flag: '🇳🇦' },
  { name: '나우루', en: 'Nauru', code: 'NR', flag: '🇳🇷' },
  { name: '나이지리아', en: 'Nigeria', code: 'NG', flag: '🇳🇬' },
  { name: '남수단', en: 'South Sudan', code: 'SS', flag: '🇸🇸' },
  { name: '남아프리카 공화국', en: 'South Africa', code: 'ZA', flag: '🇿🇦' },
  { name: '네덜란드', en: 'Netherlands', code: 'NL', flag: '🇳🇱' },
  { name: '네팔', en: 'Nepal', code: 'NP', flag: '🇳🇵', isMajor: true },
  { name: '노르웨이', en: 'Norway', code: 'NO', flag: '🇳🇴' },
  { name: '뉴질랜드', en: 'New Zealand', code: 'NZ', flag: '🇳🇿' },
  { name: '니제르', en: 'Niger', code: 'NE', flag: '🇳🇪' },
  { name: '니카라과', en: 'Nicaragua', code: 'NI', flag: '🇳🇮' },
  { name: '대만(타이완)', en: 'Taiwan', code: 'TW', flag: '🇹🇼' },
  { name: '대한민국', en: 'South Korea', code: 'KR', flag: '🇰🇷' },
  { name: '덴마크', en: 'Denmark', code: 'DK', flag: '🇩🇰' },
  { name: '도미니카 공화국', en: 'Dominican Republic', code: 'DO', flag: '🇩🇴' },
  { name: '도미니카 연방', en: 'Dominica', code: 'DM', flag: '🇩🇲' },
  { name: '독일', en: 'Germany', code: 'DE', flag: '🇩🇪' },
  { name: '동티모르', en: 'Timor-Leste', code: 'TL', flag: '🇹🇱', isMajor: true },
  { name: '라오스', en: 'Laos', code: 'LA', flag: '🇱🇦', isMajor: true },
  { name: '라이베리아', en: 'Liberia', code: 'LR', flag: '🇱🇷' },
  { name: '라트비아', en: 'Latvia', code: 'LV', flag: '🇱🇻' },
  { name: '러시아', en: 'Russia', code: 'RU', flag: '🇷🇺' },
  { name: '레바논', en: 'Lebanon', code: 'LB', flag: '🇱🇧' },
  { name: '레소토', en: 'Lesotho', code: 'LS', flag: '🇱🇸' },
  { name: '루마니아', en: 'Romania', code: 'RO', flag: '🇷🇴' },
  { name: '룩셈부르크', en: 'Luxembourg', code: 'LU', flag: '🇱🇺' },
  { name: '르완다', en: 'Rwanda', code: 'RW', flag: '🇷🇼' },
  { name: '리비아', en: 'Libya', code: 'LY', flag: '🇱🇾' },
  { name: '리투아니아', en: 'Lithuania', code: 'LT', flag: '🇱🇹' },
  { name: '리히텐슈타인', en: 'Liechtenstein', code: 'LI', flag: '🇱🇮' },
  { name: '마다가스카르', en: 'Madagascar', code: 'MG', flag: '🇲🇬' },
  { name: '마셜 제도', en: 'Marshall Islands', code: 'MH', flag: '🇲🇭' },
  { name: '말라위', en: 'Malawi', code: 'MW', flag: '🇲🇼' },
  { name: '말레이시아', en: 'Malaysia', code: 'MY', flag: '🇲🇾' },
  { name: '말리', en: 'Mali', code: 'ML', flag: '🇲🇱' },
  { name: '멕시코', en: 'Mexico', code: 'MX', flag: '🇲🇽' },
  { name: '모나코', en: 'Monaco', code: 'MC', flag: '🇲🇨' },
  { name: '모로코', en: 'Morocco', code: 'MA', flag: '🇲🇦' },
  { name: '모리셔스', en: 'Mauritius', code: 'MU', flag: '🇲🇺' },
  { name: '모리타니', en: 'Mauritania', code: 'MR', flag: '🇲🇷' },
  { name: '모잠비크', en: 'Mozambique', code: 'MZ', flag: '🇲🇿' },
  { name: '몬테네그로', en: 'Montenegro', code: 'ME', flag: '🇲🇪' },
  { name: '몰도바', en: 'Moldova', code: 'MD', flag: '🇲🇩' },
  { name: '몰디브', en: 'Maldives', code: 'MV', flag: '🇲🇻' },
  { name: '몰타', en: 'Malta', code: 'MT', flag: '🇲🇹' },
  { name: '몽골', en: 'Mongolia', code: 'MN', flag: '🇲🇳', isMajor: true },
  { name: '미국', en: 'United States', code: 'US', flag: '🇺🇸' },
  { name: '미얀마', en: 'Myanmar', code: 'MM', flag: '🇲🇲', isMajor: true },
  { name: '미크로네시아', en: 'Micronesia', code: 'FM', flag: '🇫🇲' },
  { name: '바누아투', en: 'Vanuatu', code: 'VU', flag: '🇻🇺' },
  { name: '바레인', en: 'Bahrain', code: 'BH', flag: '🇧🇭' },
  { name: '바베이도스', en: 'Barbados', code: 'BB', flag: '🇧🇧' },
  { name: '바하마', en: 'Bahamas', code: 'BS', flag: '🇧🇸' },
  { name: '방글라데시', en: 'Bangladesh', code: 'BD', flag: '🇧🇩', isMajor: true },
  { name: '베냉', en: 'Benin', code: 'BJ', flag: '🇧🇯' },
  { name: '베네수엘라', en: 'Venezuela', code: 'VE', flag: '🇻🇪' },
  { name: '베트남', en: 'Vietnam', code: 'VN', flag: '🇻🇳', isMajor: true },
  { name: '벨기에', en: 'Belgium', code: 'BE', flag: '🇧🇪' },
  { name: '벨라루스', en: 'Belarus', code: 'BY', flag: '🇧🇾' },
  { name: '벨리즈', en: 'Belize', code: 'BZ', flag: '🇧🇿' },
  { name: '보스니아 헤르체고비나', en: 'Bosnia and Herzegovina', code: 'BA', flag: '🇧🇦' },
  { name: '보츠와나', en: 'Botswana', code: 'BW', flag: '🇧🇼' },
  { name: '볼리비아', en: 'Bolivia', code: 'BO', flag: '🇧🇴' },
  { name: '부룬디', en: 'Burundi', code: 'BI', flag: '🇧🇮' },
  { name: '부르키나파소', en: 'Burkina Faso', code: 'BF', flag: '🇧🇫' },
  { name: '부탄', en: 'Bhutan', code: 'BT', flag: '🇧🇹' },
  { name: '북마케도니아', en: 'North Macedonia', code: 'MK', flag: '🇲🇰' },
  { name: '불가리아', en: 'Bulgaria', code: 'BG', flag: '🇧🇬' },
  { name: '브라질', en: 'Brazil', code: 'BR', flag: '🇧🇷' },
  { name: '브루나이', en: 'Brunei', code: 'BN', flag: '🇧🇳' },
  { name: '사모아', en: 'Samoa', code: 'WS', flag: '🇼🇸' },
  { name: '사우디아라비아', en: 'Saudi Arabia', code: 'SA', flag: '🇸🇦' },
  { name: '산마리노', en: 'San Marino', code: 'SM', flag: '🇸🇲' },
  { name: '상투메 프린시페', en: 'Sao Tome and Principe', code: 'ST', flag: '🇸🇹' },
  { name: '세네갈', en: 'Senegal', code: 'SN', flag: '🇸🇳' },
  { name: '세르비아', en: 'Serbia', code: 'RS', flag: '🇷🇸' },
  { name: '세이셸', en: 'Seychelles', code: 'SC', flag: '🇸🇨' },
  { name: '세인트루시아', en: 'Saint Lucia', code: 'LC', flag: '🇱🇨' },
  { name: '세인트빈센트 그레나딘', en: 'Saint Vincent and the Grenadines', code: 'VC', flag: '🇻🇨' },
  { name: '세인트키츠 네비스', en: 'Saint Kitts and Nevis', code: 'KN', flag: '🇰🇳' },
  { name: '소말리아', en: 'Somalia', code: 'SO', flag: '🇸🇴' },
  { name: '솔로몬 제도', en: 'Solomon Islands', code: 'SB', flag: '🇸🇧' },
  { name: '수단', en: 'Sudan', code: 'SD', flag: '🇸🇩' },
  { name: '수리남', en: 'Suriname', code: 'SR', flag: '🇸🇷' },
  { name: '스리랑카', en: 'Sri Lanka', code: 'LK', flag: '🇱🇰', isMajor: true },
  { name: '스웨덴', en: 'Sweden', code: 'SE', flag: '🇸🇪' },
  { name: '스위스', en: 'Switzerland', code: 'CH', flag: '🇨🇭' },
  { name: '스페인', en: 'Spain', code: 'ES', flag: '🇪🇸' },
  { name: '슬로바키아', en: 'Slovakia', code: 'SK', flag: '🇸🇰' },
  { name: '슬로베니아', en: 'Slovenia', code: 'SI', flag: '🇸🇮' },
  { name: '시리아', en: 'Syria', code: 'SY', flag: '🇸🇾' },
  { name: '시에라리온', en: 'Sierra Leone', code: 'SL', flag: '🇸🇱' },
  { name: '싱가포르', en: 'Singapore', code: 'SG', flag: '🇸🇬' },
  { name: '아랍에미리트', en: 'United Arab Emirates', code: 'AE', flag: '🇦🇪' },
  { name: '아르메니아', en: 'Armenia', code: 'AM', flag: '🇦🇲' },
  { name: '아르헨티나', en: 'Argentina', code: 'AR', flag: '🇦🇷' },
  { name: '아이슬란드', en: 'Iceland', code: 'IS', flag: '🇮🇸' },
  { name: '아이티', en: 'Haiti', code: 'HT', flag: '🇭🇹' },
  { name: '아일랜드', en: 'Ireland', code: 'IE', flag: '🇮🇪' },
  { name: '아프가니스탄', en: 'Afghanistan', code: 'AF', flag: '🇦🇫' },
  { name: '알제리', en: 'Algeria', code: 'DZ', flag: '🇩🇿' },
  { name: '알바니아', en: 'Albania', code: 'AL', flag: '🇦🇱' },
  { name: '앙골라', en: 'Angola', code: 'AO', flag: '🇦🇴' },
  { name: '앤티가 바부다', en: 'Antigua and Barbuda', code: 'AG', flag: '🇦🇬' },
  { name: '에리트레아', en: 'Eritrea', code: 'ER', flag: '🇪🇷' },
  { name: '에스와티니', en: 'Eswatini', code: 'SZ', flag: '🇸🇿' },
  { name: '에스토니아', en: 'Estonia', code: 'EE', flag: '🇪🇪' },
  { name: '에콰도르', en: 'Ecuador', code: 'EC', flag: '🇪🇨' },
  { name: '에티오피아', en: 'Ethiopia', code: 'ET', flag: '🇪🇹' },
  { name: '엘살바도르', en: 'El Salvador', code: 'SV', flag: '🇸🇻' },
  { name: '영국', en: 'United Kingdom', code: 'GB', flag: '🇬🇧' },
  { name: '예멘', en: 'Yemen', code: 'YE', flag: '🇾🇪' },
  { name: '오만', en: 'Oman', code: 'OM', flag: '🇴🇲' },
  { name: '오스트레일리아(호주)', en: 'Australia', code: 'AU', flag: '🇦🇺' },
  { name: '오스트리아', en: 'Austria', code: 'AT', flag: '🇦🇹' },
  { name: '온두라스', en: 'Honduras', code: 'HN', flag: '🇭🇳' },
  { name: '요르단', en: 'Jordan', code: 'JO', flag: '🇯🇴' },
  { name: '우간다', en: 'Uganda', code: 'UG', flag: '🇺🇬' },
  { name: '우루과이', en: 'Uruguay', code: 'UY', flag: '🇺🇾' },
  { name: '우즈베키스탄', en: 'Uzbekistan', code: 'UZ', flag: '🇺🇿', isMajor: true },
  { name: '우크라이나', en: 'Ukraine', code: 'UA', flag: '🇺🇦' },
  { name: '이라크', en: 'Iraq', code: 'IQ', flag: '🇮🇶' },
  { name: '이란', en: 'Iran', code: 'IR', flag: '🇮🇷' },
  { name: '이스라엘', en: 'Israel', code: 'IL', flag: '🇮🇱' },
  { name: '이집트', en: 'Egypt', code: 'EG', flag: '🇪🇬' },
  { name: '이탈리아', en: 'Italy', code: 'IT', flag: '🇮🇹' },
  { name: '인도', en: 'India', code: 'IN', flag: '🇮🇳' },
  { name: '인도네시아', en: 'Indonesia', code: 'ID', flag: '🇮🇩', isMajor: true },
  { name: '일본', en: 'Japan', code: 'JP', flag: '🇯🇵' },
  { name: '자메이카', en: 'Jamaica', code: 'JM', flag: '🇯🇲' },
  { name: '잠비아', en: 'Zambia', code: 'ZM', flag: '🇿🇲' },
  { name: '적도 기니', en: 'Equatorial Guinea', code: 'GQ', flag: '🇬🇶' },
  { name: '조지아', en: 'Georgia', code: 'GE', flag: '🇬🇪' },
  { name: '중앙아프리카 공화국', en: 'Central African Republic', code: 'CF', flag: '🇨🇫' },
  { name: '중국', en: 'China', code: 'CN', flag: '🇨🇳', isMajor: true },
  { name: '지부티', en: 'Djibouti', code: 'DJ', flag: '🇩🇯' },
  { name: '짐바브웨', en: 'Zimbabwe', code: 'ZW', flag: '🇿🇼' },
  { name: '차드', en: 'Chad', code: 'TD', flag: '🇹🇩' },
  { name: '체코', en: 'Czech Republic', code: 'CZ', flag: '🇨🇿' },
  { name: '칠레', en: 'Chile', code: 'CL', flag: '🇨🇱' },
  { name: '카메룬', en: 'Cameroon', code: 'CM', flag: '🇨🇲' },
  { name: '카보베르데', en: 'Cape Verde', code: 'CV', flag: '🇨🇻' },
  { name: '카자흐스탄', en: 'Kazakhstan', code: 'KZ', flag: '🇰🇿' },
  { name: '카타르', en: 'Qatar', code: 'QA', flag: '🇶🇦' },
  { name: '캄보디아', en: 'Cambodia', code: 'KH', flag: '🇰🇭', isMajor: true },
  { name: '캐나다', en: 'Canada', code: 'CA', flag: '🇨🇦' },
  { name: '케냐', en: 'Kenya', code: 'KE', flag: '🇰🇪' },
  { name: '코모로', en: 'Comoros', code: 'KM', flag: '🇰🇲' },
  { name: '코스타리카', en: 'Costa Rica', code: 'CR', flag: '🇨🇷' },
  { name: '코트디부아르', en: "Cote d'Ivoire", code: 'CI', flag: '🇨🇮' },
  { name: '콜롬비아', en: 'Colombia', code: 'CO', flag: '🇨🇴' },
  { name: '콩고 공화국', en: 'Republic of the Congo', code: 'CG', flag: '🇨🇬' },
  { name: '콩고 민주 공화국', en: 'DR Congo', code: 'CD', flag: '🇨🇩' },
  { name: '쿠바', en: 'Cuba', code: 'CU', flag: '🇨🇺' },
  { name: '쿠웨이트', en: 'Kuwait', code: 'KW', flag: '🇰🇼' },
  { name: '크로아티아', en: 'Croatia', code: 'HR', flag: '🇭🇷' },
  { name: '키르기스스탄', en: 'Kyrgyzstan', code: 'KG', flag: '🇰🇬', isMajor: true },
  { name: '키리바시', en: 'Kiribati', code: 'KI', flag: '🇰🇮' },
  { name: '키프로스', en: 'Cyprus', code: 'CY', flag: '🇨🇾' },
  { name: '타지키스탄', en: 'Tajikistan', code: 'TJ', flag: '🇹🇯' },
  { name: '탄자니아', en: 'Tanzania', code: 'TZ', flag: '🇹🇿' },
  { name: '태국', en: 'Thailand', code: 'TH', flag: '🇹🇭', isMajor: true },
  { name: '터키(튀르키예)', en: 'Turkey', code: 'TR', flag: '🇹🇷' },
  { name: '토고', en: 'Togo', code: 'TG', flag: '🇹🇬' },
  { name: '통가', en: 'Tonga', code: 'TO', flag: '🇹🇴' },
  { name: '투르크메니스탄', en: 'Turkmenistan', code: 'TM', flag: '🇹🇲' },
  { name: '투발루', en: 'Tuvalu', code: 'TV', flag: '🇹🇻' },
  { name: '튀니지', en: 'Tunisia', code: 'TN', flag: '🇹🇳' },
  { name: '트리니다드 토바고', en: 'Trinidad and Tobago', code: 'TT', flag: '🇹🇹' },
  { name: '파나마', en: 'Panama', code: 'PA', flag: '🇵🇦' },
  { name: '파라과이', en: 'Paraguay', code: 'PY', flag: '🇵🇾' },
  { name: '파키스탄', en: 'Pakistan', code: 'PK', flag: '🇵🇰', isMajor: true },
  { name: '파푸아뉴기니', en: 'Papua New Guinea', code: 'PG', flag: '🇵🇬' },
  { name: '팔라우', en: 'Palau', code: 'PW', flag: '🇵🇼' },
  { name: '팔레스타인', en: 'Palestine', code: 'PS', flag: '🇵🇸' },
  { name: '페루', en: 'Peru', code: 'PE', flag: '🇵🇪' },
  { name: '포르투갈', en: 'Portugal', code: 'PT', flag: '🇵🇹' },
  { name: '폴란드', en: 'Poland', code: 'PL', flag: '🇵🇱' },
  { name: '프랑스', en: 'France', code: 'FR', flag: '🇫🇷' },
  { name: '피지', en: 'Fiji', code: 'FJ', flag: '🇫🇯' },
  { name: '핀란드', en: 'Finland', code: 'FI', flag: '🇫🇮' },
  { name: '필리핀', en: 'Philippines', code: 'PH', flag: '🇵🇭', isMajor: true },
  { name: '헝가리', en: 'Hungary', code: 'HU', flag: '🇭🇺' },
  { name: '홍콩', en: 'Hong Kong', code: 'HK', flag: '🇭🇰' },
];

/**
 * 검색어(query)로 국가 필터링 (한국어명 부분일치, 영문명 부분일치, 대소문자 무시)
 */
export function searchCountries(query: string): Country[] {
  const q = query.trim().toLowerCase();
  if (!q) return ALL_COUNTRIES;

  return ALL_COUNTRIES.filter((c) => {
    return (
      c.name.toLowerCase().includes(q) ||
      c.en.toLowerCase().includes(q) ||
      c.code.toLowerCase().includes(q)
    );
  });
}
