/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExitcheckRouteImport } from './routes/exitcheck'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PaycheckRouteImport } from './routes/paycheck'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as TaxcheckRouteImport } from './routes/taxcheck'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExitcheckRoute = ExitcheckRouteImport.update({
  id: '/exitcheck',
  path: '/exitcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PaycheckRoute = PaycheckRouteImport.update({
  id: '/paycheck',
  path: '/paycheck',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxcheckRoute = TaxcheckRouteImport.update({
  id: '/taxcheck',
  path: '/taxcheck',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/exitcheck': typeof ExitcheckRoute
  '/onboarding': typeof OnboardingRoute
  '/paycheck': typeof PaycheckRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/taxcheck': typeof TaxcheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/exitcheck': typeof ExitcheckRoute
  '/onboarding': typeof OnboardingRoute
  '/paycheck': typeof PaycheckRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/taxcheck': typeof TaxcheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/exitcheck': typeof ExitcheckRoute
  '/onboarding': typeof OnboardingRoute
  '/paycheck': typeof PaycheckRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/taxcheck': typeof TaxcheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/exitcheck'
    | '/onboarding'
    | '/paycheck'
    | '/profile'
    | '/records'
    | '/taxcheck'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/exitcheck'
    | '/onboarding'
    | '/paycheck'
    | '/profile'
    | '/records'
    | '/taxcheck'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/exitcheck'
    | '/onboarding'
    | '/paycheck'
    | '/profile'
    | '/records'
    | '/taxcheck'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  ExitcheckRoute: typeof ExitcheckRoute
  OnboardingRoute: typeof OnboardingRoute
  PaycheckRoute: typeof PaycheckRoute
  ProfileRoute: typeof ProfileRoute
  RecordsRoute: typeof RecordsRoute
  TaxcheckRoute: typeof TaxcheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exitcheck': {
      id: '/exitcheck'
      path: '/exitcheck'
      fullPath: '/exitcheck'
      preLoaderRoute: typeof ExitcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paycheck': {
      id: '/paycheck'
      path: '/paycheck'
      fullPath: '/paycheck'
      preLoaderRoute: typeof PaycheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxcheck': {
      id: '/taxcheck'
      path: '/taxcheck'
      fullPath: '/taxcheck'
      preLoaderRoute: typeof TaxcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  ExitcheckRoute: ExitcheckRoute,
  OnboardingRoute: OnboardingRoute,
  PaycheckRoute: PaycheckRoute,
  ProfileRoute: ProfileRoute,
  RecordsRoute: RecordsRoute,
  TaxcheckRoute: TaxcheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
